apiVersion: apps/v1
kind: Deployment
metadata:
  name: nudjkk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nudjkk
  template:
    metadata:
      labels:
        app: nudjkk
    spec:
      containers:
      - image: okteto.dev/nudjkk:latest
        name: nudjkk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "86646e57-984f-46f9-a85b-205196321b35"
        - name: Vless_Path
          value: "/vl1314rrfd"
        - name: Vmess_UUID
          value: "86646e57-984f-46f9-a85b-205196321b35"
        - name: Vmess_Path
          value: "/vm2425eeds"
        - name: Share_Path
          value: "/v2link"
